//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRCalculatorService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APRCalculatorService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  10.90.
        /// </summary>
        internal static string APRClassicAverage {
            get {
                return ResourceManager.GetString("APRClassicAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.90.
        /// </summary>
        internal static string APRClassicExcellent {
            get {
                return ResourceManager.GetString("APRClassicExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  9.50.
        /// </summary>
        internal static string APRClassicGood {
            get {
                return ResourceManager.GetString("APRClassicGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  12.00.
        /// </summary>
        internal static string APRClassicPoor {
            get {
                return ResourceManager.GetString("APRClassicPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  9.90.
        /// </summary>
        internal static string APRModernClassicAverage {
            get {
                return ResourceManager.GetString("APRModernClassicAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.40.
        /// </summary>
        internal static string APRModernClassicExcellent {
            get {
                return ResourceManager.GetString("APRModernClassicExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.90.
        /// </summary>
        internal static string APRModernClassicGood {
            get {
                return ResourceManager.GetString("APRModernClassicGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  10.90.
        /// </summary>
        internal static string APRModernClassicPoor {
            get {
                return ResourceManager.GetString("APRModernClassicPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.90.
        /// </summary>
        internal static string APRNewAverage {
            get {
                return ResourceManager.GetString("APRNewAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  7.90.
        /// </summary>
        internal static string APRNewExcellent {
            get {
                return ResourceManager.GetString("APRNewExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.40.
        /// </summary>
        internal static string APRNewGood {
            get {
                return ResourceManager.GetString("APRNewGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  9.90.
        /// </summary>
        internal static string APRNewPoor {
            get {
                return ResourceManager.GetString("APRNewPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.90.
        /// </summary>
        internal static string APRUsedAverage {
            get {
                return ResourceManager.GetString("APRUsedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  7.90.
        /// </summary>
        internal static string APRUsedExcellent {
            get {
                return ResourceManager.GetString("APRUsedExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  8.40.
        /// </summary>
        internal static string APRUsedGood {
            get {
                return ResourceManager.GetString("APRUsedGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  9.90.
        /// </summary>
        internal static string APRUsedPoor {
            get {
                return ResourceManager.GetString("APRUsedPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTgvSkJSYXBpOmRvd2pvbmVz.
        /// </summary>
        internal static string Base64UserNameAndPassword {
            get {
                return ResourceManager.GetString("Base64UserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3MVG98_Psg5cppyZfJEApW7U2G8IR1psuxMGd1x6X40F7PXJfAh29vCXBJRvXf4rjdif.EqgKq5q.lCN5koSQ.
        /// </summary>
        internal static string ConsumerKey {
            get {
                return ResourceManager.GetString("ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3MVG92H4TjwUcLlLvIMWkOuic3VGZKIMuu_rq3QYHmBoPBEomPE0KPtbJYkWiBECaHpxPM58X_HbcttFnN.Qk.
        /// </summary>
        internal static string ConsumerKey_test {
            get {
                return ResourceManager.GetString("ConsumerKey_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4775424908946684934.
        /// </summary>
        internal static string ConsumerSecret {
            get {
                return ResourceManager.GetString("ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8782298419356568039.
        /// </summary>
        internal static string ConsumerSecret_test {
            get {
                return ResourceManager.GetString("ConsumerSecret_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 295.
        /// </summary>
        internal static string DocFee {
            get {
                return ResourceManager.GetString("DocFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IncludeVATOnYearlyAdminFee {
            get {
                return ResourceManager.GetString("IncludeVATOnYearlyAdminFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IncludeYearlyAdminFee {
            get {
                return ResourceManager.GetString("IncludeYearlyAdminFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        internal static string OptionToPurchaseFee {
            get {
                return ResourceManager.GetString("OptionToPurchaseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Password_test {
            get {
                return ResourceManager.GetString("Password_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SecurityToken {
            get {
                return ResourceManager.GetString("SecurityToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SecurityToken_test {
            get {
                return ResourceManager.GetString("SecurityToken_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheiner.david@gmail.com.jbr.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheiner.david@gmail.com.jbrdev.
        /// </summary>
        internal static string Username_test {
            get {
                return ResourceManager.GetString("Username_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string VATPercent {
            get {
                return ResourceManager.GetString("VATPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string YearlyAdminFee {
            get {
                return ResourceManager.GetString("YearlyAdminFee", resourceCulture);
            }
        }
    }
}
