//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowJones.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DowJones.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTgvSkJSYXBpOmRvd2pvbmVz.
        /// </summary>
        internal static string Base64UserNameAndPassword {
            get {
                return ResourceManager.GetString("Base64UserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djrc.api.test.dowjones.com/v1/.
        /// </summary>
        internal static string dowJonesURL {
            get {
                return ResourceManager.GetString("dowJonesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/entity-name/.
        /// </summary>
        internal static string urlCompany {
            get {
                return ResourceManager.GetString("urlCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/person-name/.
        /// </summary>
        internal static string urlCustomer {
            get {
                return ResourceManager.GetString("urlCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/records/.
        /// </summary>
        internal static string urlId {
            get {
                return ResourceManager.GetString("urlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEID.
        /// </summary>
        internal static string UrlIdRestfulName {
            get {
                return ResourceManager.GetString("UrlIdRestfulName", resourceCulture);
            }
        }
    }
}
